name: Dependency Check

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Dependency-Check
        run: |
          wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.2.2-release.zip
          unzip dependency-check-6.2.2-release.zip -d dependency-check

      - name: Run Dependency-Check Scan
        run: |
          cd dependency-check
          chmod +x dependency-check.sh
          ./bin/dependency-check.sh --scan /path/to/your/project --format HTML --output /path/to/dependency-check-report.html

      - name: Save Dependency-Check Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: /path/to/dependency-check-report.html
