name: Dependency Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Run Dependency-Check
      run: |
        wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.4-release.zip
        Expand-Archive -Path .\dependency-check-6.1.4-release.zip -DestinationPath .\dependency-check
        .\dependency-check\bin\dependency-check.bat --project "Juice Shop" --scan . --out .\dependency-check-report -f HTML
