name: GitHub Actions Demo with CodeQL

on:
  push:
    branches:
      - main

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [javascript] # You can add more languages if needed
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          args: --format=sarif --sarif-category=Security --output=codeql-results.sarif  

      - name: Upload CodeQL Results
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: codeql-results.sarif
